package com.weichi.erp.domain;

public class Carousel extends SuperDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.img_name
     *
     * @mbggenerated Wed Aug 01 10:57:31 CST 2018
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.img_url
     *
     * @mbggenerated Wed Aug 01 10:57:31 CST 2018
     */
    private String imgUrl;

    private int orderNum;
    private String imgLink;
    private String enableFlag;

    public int getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(int orderNum) {
        this.orderNum = orderNum;
    }

    public String getImgLink() {
        return imgLink;
    }

    public void setImgLink(String imgLink) {
        this.imgLink = imgLink;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.img_name
     *
     * @return the value of carousel.img_name
     * @mbggenerated Wed Aug 01 10:57:31 CST 2018
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.img_name
     *
     * @param imgName the value for carousel.img_name
     * @mbggenerated Wed Aug 01 10:57:31 CST 2018
     */
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.img_url
     *
     * @return the value of carousel.img_url
     * @mbggenerated Wed Aug 01 10:57:31 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.img_url
     *
     * @param imgUrl the value for carousel.img_url
     * @mbggenerated Wed Aug 01 10:57:31 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
}