package com.weichi.erp.domain;

public class Jrebel extends SuperDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrebel.defined_user_id
     *
     * @mbggenerated Thu Aug 30 18:07:59 CST 2018
     */
    private String definedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrebel.token
     *
     * @mbggenerated Thu Aug 30 18:07:59 CST 2018
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrebel.defined_user_id
     *
     * @return the value of jrebel.defined_user_id
     * @mbggenerated Thu Aug 30 18:07:59 CST 2018
     */
    public String getDefinedUserId() {
        return definedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrebel.defined_user_id
     *
     * @param definedUserId the value for jrebel.defined_user_id
     * @mbggenerated Thu Aug 30 18:07:59 CST 2018
     */
    public void setDefinedUserId(String definedUserId) {
        this.definedUserId = definedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrebel.token
     *
     * @return the value of jrebel.token
     * @mbggenerated Thu Aug 30 18:07:59 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrebel.token
     *
     * @param token the value for jrebel.token
     * @mbggenerated Thu Aug 30 18:07:59 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }
}