package com.weichi.erp.domain;

public class Product extends SuperDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_abstract
     *
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    private String productAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.thumbnail_url
     *
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    private String thumbnailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_detail
     *
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    private String productDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_abstract
     *
     * @return the value of product.product_abstract
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public String getProductAbstract() {
        return productAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_abstract
     *
     * @param productAbstract the value for product.product_abstract
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public void setProductAbstract(String productAbstract) {
        this.productAbstract = productAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.thumbnail_url
     *
     * @return the value of product.thumbnail_url
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.thumbnail_url
     *
     * @param thumbnailUrl the value for product.thumbnail_url
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_detail
     *
     * @return the value of product.product_detail
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public String getProductDetail() {
        return productDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_detail
     *
     * @param productDetail the value for product.product_detail
     * @mbggenerated Wed Aug 01 11:22:13 CST 2018
     */
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail;
    }
}