package com.weichi.erp.domain;

import java.math.BigDecimal;

public class SoldPrice extends SuperDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sold_price.seller_name
     *
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sold_price.sold_count
     *
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    private Long soldCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sold_price.rmb_num
     *
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    private BigDecimal rmbNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sold_price.seller_name
     *
     * @return the value of sold_price.seller_name
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sold_price.seller_name
     *
     * @param sellerName the value for sold_price.seller_name
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sold_price.sold_count
     *
     * @return the value of sold_price.sold_count
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    public Long getSoldCount() {
        return soldCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sold_price.sold_count
     *
     * @param soldCount the value for sold_price.sold_count
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    public void setSoldCount(Long soldCount) {
        this.soldCount = soldCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sold_price.rmb_num
     *
     * @return the value of sold_price.rmb_num
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    public BigDecimal getRmbNum() {
        return rmbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sold_price.rmb_num
     *
     * @param rmbNum the value for sold_price.rmb_num
     * @mbggenerated Mon Oct 08 17:17:03 CST 2018
     */
    public void setRmbNum(BigDecimal rmbNum) {
        this.rmbNum = rmbNum;
    }
}