package com.weichi.erp.domain;

public class TaobaoOrder extends SuperDomain<TaobaoOrder> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.order_num
     *
     * @mbggenerated Thu Sep 20 15:53:04 CST 2018
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.enable_flag
     *
     * @mbggenerated Thu Sep 20 15:53:04 CST 2018
     */
    private String enableFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.order_num
     *
     * @return the value of taobao_order.order_num
     * @mbggenerated Thu Sep 20 15:53:04 CST 2018
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.order_num
     *
     * @param orderNum the value for taobao_order.order_num
     * @mbggenerated Thu Sep 20 15:53:04 CST 2018
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.enable_flag
     *
     * @return the value of taobao_order.enable_flag
     * @mbggenerated Thu Sep 20 15:53:04 CST 2018
     */
    public String getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.enable_flag
     *
     * @param enableFlag the value for taobao_order.enable_flag
     * @mbggenerated Thu Sep 20 15:53:04 CST 2018
     */
    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }
}